//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHealthPredication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartHealthPredicationEntities : DbContext
    {
        public SmartHealthPredicationEntities()
            : base("name=SmartHealthPredicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDiseases> tblDiseases { get; set; }
        public virtual DbSet<tblDiseasesPredictionList> tblDiseasesPredictionList { get; set; }
        public virtual DbSet<tblDoctorAppointment> tblDoctorAppointment { get; set; }
        public virtual DbSet<tblSymptomsList> tblSymptomsList { get; set; }
        public virtual DbSet<tblSymptomsPrediction> tblSymptomsPrediction { get; set; }
        public virtual DbSet<tblUserRegistration> tblUserRegistration { get; set; }
        public virtual DbSet<View_AppoinmentList> View_AppoinmentList { get; set; }
        public virtual DbSet<View_DiseasesPrediction> View_DiseasesPrediction { get; set; }
        public virtual DbSet<tblUserRole> tblUserRole { get; set; }
        public virtual DbSet<tblFeedBack> tblFeedBack { get; set; }
    }
}
