//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHealthPredication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctorAppointment
    {
        public int AppointmentID { get; set; }
        public Nullable<int> PaitentID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> DiseasesPredictionID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string Status { get; set; }
    
        public virtual tblDiseasesPredictionList tblDiseasesPredictionList { get; set; }
        public virtual tblUserRegistration tblUserRegistration { get; set; }
        public virtual tblUserRegistration tblUserRegistration1 { get; set; }
    }
}
