//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHealthPredication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiseases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDiseases()
        {
            this.tblDiseasesPredictionList = new HashSet<tblDiseasesPredictionList>();
        }
    
        public int DiseasesID { get; set; }
        public string DiseasesName { get; set; }
        public string images { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiseasesPredictionList> tblDiseasesPredictionList { get; set; }
    }
}
