//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHealthPredication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiseasesPredictionList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDiseasesPredictionList()
        {
            this.tblDoctorAppointment = new HashSet<tblDoctorAppointment>();
        }
    
        public int DiseasesPredictionListID { get; set; }
        public Nullable<int> SymptomsPredictionID { get; set; }
        public Nullable<int> DiseasesID { get; set; }
        public string Status { get; set; }
    
        public virtual tblDiseases tblDiseases { get; set; }
        public virtual tblSymptomsPrediction tblSymptomsPrediction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDoctorAppointment> tblDoctorAppointment { get; set; }
    }
}
