//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHealthPredication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserRegistration()
        {
            this.tblDoctorAppointment = new HashSet<tblDoctorAppointment>();
            this.tblDoctorAppointment1 = new HashSet<tblDoctorAppointment>();
            this.tblFeedBack = new HashSet<tblFeedBack>();
            this.tblFeedBack1 = new HashSet<tblFeedBack>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string UserFullName { get; set; }
        public string EmailID { get; set; }
        public string MoblieNumber { get; set; }
        public string AdharCardNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public string Designation { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDoctorAppointment> tblDoctorAppointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDoctorAppointment> tblDoctorAppointment1 { get; set; }
        public virtual tblUserRole tblUserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFeedBack> tblFeedBack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFeedBack> tblFeedBack1 { get; set; }
    }
}
