//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHealthPredication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DiseasesPrediction
    {
        public int DiseasesPredictionListID { get; set; }
        public Nullable<int> SymptomsPredictionID { get; set; }
        public string SymptomsPredictionName { get; set; }
        public Nullable<int> DiseasesID { get; set; }
        public string DiseasesName { get; set; }
        public string images { get; set; }
    }
}
